---
title: "Resources"
output: html_document
---

### R & R-Studio

[R](http://www.r-project.org) é uma linguagem de programação em mcódigo livre que hoje é a melhor ferramenta de análises de dados em ecologia;
[R-studio](http://www.rstudio.com) é a interface gráfica que facilita a vida quando trabalhamos com **R** e no nosso caso vai ser fundamental para construir os relatórios que serão _sua prórpia história_ na disciplina []().

### Recursos adiconais para R

1. O Google sabe tudo, dê uma _googlada_ com seu problema e terá uma solução
2. Há tantos cursos, do básico ao avançado em R, de graça na internet e em todas as línguas que fica até difífil escolher, mas, aqui vão alguns:
  2.1. [Maurício Vancine](https://mauriciovancine.github.io/) é um biólogo como nós e tem uma quantidade enorme de material para ensino de estatística. Especialmente análises espaciais. Ele foi minha inspiração para organizar essa bagaça toda online e muita coisa aqui está "copiada" dele.
  2.2. [CrumpLab](https://crumplab.github.io/Courses.html) é um lab de psiocologia liderado po **Matthew Crump** da Brooklyn College, NY EUA. Outra parte desse curso foin inspirda na forma como eles dão os cursos por lá, com forte ênfase na reporducibilidade.
3. [Bookdown](https://bookdown.org/yihui/rmarkdown/) éum livro online feito pelo próprio criador do RMarkdown. Tem tudo lá!

### Recursos de aulas online em português e inglês para ecólogos

1. [Vários cursos online de estatística em R para ecólogos](https://mauriciovancine.github.io/pt/post/general-courses-online/) compilado, claro por [Maurício Vancine](https://mauriciovancine.github.io/)
2. [Carpentries](https://datacarpentry.org/lessons/#ecology-workshop) aqui tem cursos de todos tipo com R, vale a pena.
3. [David Zelený](https://www.davidzeleny.net/anadat-r/doku.php/en:start) Esse site é de uma fera da ecologica numérica. Tem coisa dele aqui também.

